[finance]
developer_rate = 100.0
currency = "USD"
hours_to_fix_god_class = 40.0
hours_to_fix_secret = 4.0
hours_to_fix_license = 160.0
hours_to_fix_cycle = 16.0
hours_to_fix_test = 2.0

[risk]
max_complexity = 20
max_file_lines = 1000
